In [14]:
import numpy as np
from Values import Values

class Action():
    
    def __init__(self,name, agent, v_index):
        
        '''
        generic action class, similar to activity but not of agent type
        '''
        self.name = name
        self.agent = agent            #tie it to a given agent
        self.v_index = v_index          #index of value to be satisfied
        self.counter = 0              #for histogramming purposes
    
    def precondition(self):
        
        return True
        
    def do(self):
        
        self.agent.values.val_t[self.v_index] += self.agent.values.val_sat[self.v_index]
        self.counter += 1

class valuesTest():
    
    def __init__(self, decay, se, st, c, otc):
        
        self.values = Values(decay, se, st, c, otc, self)
        self.actions = set([])
        for i in range(4):
            self.actions.add(Action('action'+str(i), self, i))
        
    
    def step(self):
        self.values.decay_val()

        #prioritize
        priority = self.values.prioritize()


        #act
        #find action that corresponds to priority
        current = None
        possible_actions = set(filter(lambda x: x.precondition(), self.actions))
        for value in priority:
                for action in possible_actions:
                    if value == action.v_index:
                        current = action
                        break
                if current != None:
                    break

        #update v_sat
        if current != None:
            #print(current.name)
            current.do()
        print(self.values.val_t)


In [18]:
test = valuesTest(10,10,10,10,10)
for i in range(10):
    test.step()
    

[140  50  50  50]
[130 130  40  40]
[120 120 120  30]
[110 110 110 110]
[190 100 100 100]
[180 180  90  90]
[170 170 170  80]
[160 160 160 160]
[240 150 150 150]
[230 230 140 140]
